[package]
name = "kwak"
version = "0.1.0"
authors = ["Dimitri Sabadie <dimitri.sabadie@gmail.com>"]

[dependencies]
clap = "2.29"
lazy_static = "1.0"
html-entities = "0.1"
rand = "0.4"
regex = "0.2"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1"
