use clap::{App, Arg};

pub fn new<'a, 'b>() -> App<'a, 'b> where 'a: 'b {
  App::new("kwak")
    .arg(Arg::with_name("host")
         .short("h")
         .long("host")
         .help("IRC server host to connect to")
         .required(true)
         .takes_value(true))
    .arg(Arg::with_name("channel")
         .short("c")
         .long("channel")
         .help("IRC channel to join upon connection")
         .required(true)
         .takes_value(true))
    .arg(Arg::with_name("nick")
         .short("n")
         .long("nick")
         .help("IRC nickname to use")
         .required(true)
         .takes_value(true))
    .arg(Arg::with_name("tells")
         .short("t")
         .long("tells_path")
         .value_name("FILE")
         .help("Path to the JSON file containing the tells")
         .takes_value(true))
    .arg(Arg::with_name("log")
         .short("l")
         .long("log_path")
         .value_name("FILE")
         .help("Path to the log")
         .takes_value(true))
    .arg(Arg::with_name("markov")
         .short("m")
         .long("markov")
         .value_name("FILE")
         .help("Path to the Markov graph")
         .takes_value(true))
}
